services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs_server
    networks:
      - web
    environment:
      PORT: 3200
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/streaming_service
      VIDEO_PATH: ./video.mp4
    volumes:
      - ./server/video.mp4:/app/video.mp4
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.server.rule=Host(`apistream.mehdify.com`)'
      - 'traefik.http.routers.server.entrypoints=websecure'
      - 'traefik.http.routers.server.tls.certresolver=myresolver'
      - 'traefik.http.services.server.loadbalancer.server.port=3200'
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vite_client
    networks:
      - web
    depends_on:
      - server
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.client.rule=Host(`stream.mehdify.com`)'
      - 'traefik.http.routers.client.entrypoints=websecure'
      - 'traefik.http.routers.client.tls.certresolver=myresolver'
      - 'traefik.http.services.client.loadbalancer.server.port=3100'
    restart: unless-stopped

networks:
  web:
    external: true
